apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: magic624/notifications:latest
          envFrom:
            - configMapRef:
                name: notification-config
            - secretRef:
                name: notification-secret
